pipeline {
    agent any
     tools { 
        maven 'Maven_Home'
        jdk 'Java_Home'
    }

    stages {
        stage('Fetching changes') {
            steps {
               git credentialsId: '64953833-6d7a-4cc4-82a2-753650dd9aba', 
               url: 'https://github.com/shanjana91/Product-API-without-Docker'
            }
        }
            stage('Build') {
            steps {
               bat 'mvn -f ProductCRUD-2/pom.xml clean install -DskipTests'
            }
        }
        stage('test') {
            steps {
               bat 'mvn -f ProductCRUD-2/pom.xml test'
            }
    }
     stage('SonarQube analysis') {
            steps {
            withSonarQubeEnv('SonarQube'){
               bat 'mvn -f ProductCRUD-2/pom.xml clean install sonar:sonar -Dsonar.login=4b896667b82e39361190abc6abdc918ef9faab7b'
            }
            }
    }
    stage("Quality Gate"){
          timeout(time: 1, unit: 'HOURS') {
              def qg = waitForQualityGate()
              if (qg.status != 'OK') {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
              }
          }
          }
    stage('deploy') {
            steps {
              deploy adapters: [tomcat8(credentialsId: '1e0ba6ff-b200-419e-856c-836927a5750c', path: '', url: 'http://localhost:8081/')],
              contextPath: 'Product API Pipeline', 
              war: '**/*.war'
            }
    }
    }
    post {
        always {
            junit 'ProductCRUD-2/*target/surefire-reports/TEST-*.xml'
        }
    }
    
}
